import { test, expect } from '@playwright/test'

test('California county snapshot searches locally without putting location in URL or network', async ({ page }) => {
  const requests = []
  page.on('request', (request) => { if (request.method() !== 'GET') requests.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('group', { name: 'Search by' })).toBeVisible()
  await page.getByLabel('California county').selectOption('Orange')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByText(/statewide licensed-facility listings for county Orange/)).toBeVisible()
  await expect(page.getByText(/ALISO RIDGE BEHAVIORAL HEALTH, LLC/i)).toBeHidden()
  expect(page.url()).not.toContain('Orange')
  expect(requests).toEqual([])
})

test('county-first search can browse official local sites by chosen city without ZIP', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Orange')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const sites = page.locator('section[aria-label="Orange County Behavioral Health Plan sites"]')
  await expect(sites.locator('article')).toHaveCount(0)
  await sites.getByLabel('Filter Orange County sites by city').selectOption('Irvine')
  await expect(sites.locator('article')).toHaveCount(1)
  await expect(sites.locator('article').first()).toContainText('Irvine')
  await expect(sites.locator('article').first().getByRole('link', { name: '949-722-7118' })).toHaveAttribute('href', 'tel:+19497227118')
  await page.getByLabel('California county').selectOption('San Diego')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const clinics = page.locator('section[aria-label="San Diego adult behavioral health clinics"]')
  await expect(clinics.getByText('20 adult clinic locations in San Diego County')).toBeVisible()
  await expect(clinics.locator('article')).toHaveCount(0)
  await clinics.getByLabel('Filter San Diego adult clinics by city').selectOption('*')
  await expect(clinics.locator('article')).toHaveCount(20)
  await clinics.getByLabel('Filter San Diego adult clinics by city').selectOption('Escondido')
  await expect(clinics.locator('article')).toHaveCount(2)
  await expect(clinics.locator('article').first().getByRole('link', { name: '(760) 480-2255' })).toHaveAttribute('href', 'tel:+17604802255')
})

test('Butte county adult outpatient centers are local, city-filtered, and removed on county change', async ({ page }) => {
  const requests = []
  page.on('request', (request) => { if (request.method() !== 'GET') requests.push(request.url()) })
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Butte')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const centers = page.locator('section[aria-label="Butte adult outpatient centers"]')
  await expect(centers).toContainText('4 adult outpatient centers')
  await expect(centers.locator('article')).toHaveCount(4)
  await centers.getByLabel('Filter Butte adult centers by city').selectOption('Paradise')
  await expect(centers.locator('article')).toHaveCount(1)
  await expect(centers).toContainText('7200 Skyway')
  await expect(centers.getByRole('link', { name: '530-877-5845' })).toHaveAttribute('href', 'tel:+15308775845')
  await centers.getByLabel('Filter Butte adult centers by city').selectOption('*')
  await expect(centers.locator('article')).toHaveCount(4)
  await page.getByLabel('California county').selectOption('Colusa')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(centers).toHaveCount(0)
  expect(requests).toEqual([])
})

test('mixed-format licensed-facility phone remains text rather than a misleading dial link', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Sacramento')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const facilities = page.locator('details[aria-label="Statewide licensed-facility snapshot"]')
  await facilities.locator(':scope > summary').click()
  const mixed = facilities.locator('article').filter({ hasText: '(916) 483-8424, 977- 0949' })
  await expect(mixed).toContainText('(916) 483-8424, 977- 0949')
  await expect(mixed.locator('a[href^="tel:"]')).toHaveCount(0)
})

test('county selection exposes LA official directory without requiring ZIP or a network request', async ({ page }) => {
  const requests = []
  page.on('request', (request) => { if (request.url().includes('/api/la-county/locations')) requests.push(request.url()) })
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Los Angeles')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.locator('section[aria-label="County mental health plan"]').getByRole('link', { name: 'official LA County provider directory' })).toHaveAttribute('href', 'https://dmh.lacounty.gov/pd/')
  expect(requests).toEqual([])
})

test('non-LA ZIP searches local records without calling the live LA API', async ({ page }) => {
  const countyRequests = []
  page.on('request', (request) => { if (request.url().includes('/api/la-county/locations')) countyRequests.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('92708')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByRole('heading', { name: /2 listed provider sites · Fountain Valley · Orange County/ })).toBeVisible()
  await expect(page.getByText(/Other licensed facilities elsewhere in Orange County/)).toHaveCount(0)
  expect(countyRequests).toEqual([])
})

test('San Diego adult clinic matches are separate from the statewide license snapshot', async ({ page }) => {
  const countyRequests = []
  page.on('request', (request) => { if (request.url().includes('/api/la-county/locations')) countyRequests.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('92025')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const clinics = page.locator('section[aria-label="San Diego adult behavioral health clinics"]')
  await expect(clinics.getByRole('heading', { name: /2 adult clinic listings for ZIP 92025/ })).toBeVisible()
  await expect(clinics.getByText('North Inland Mental Health Center', { exact: true })).toBeVisible()
  await expect(clinics.getByText('Kinesis North Escondido', { exact: true })).toBeVisible()
  await expect(clinics.getByText('Adults 18+', { exact: true })).toBeVisible()
  await expect(clinics.getByText(/County outpatient-clinic subset · Snapshot/)).toBeHidden()
  await clinics.getByText('Source & details', { exact: true }).click()
  await expect(clinics.getByText(/County outpatient-clinic subset · Snapshot/)).toBeVisible()
  await expect(page.getByRole('link', { name: 'Full San Diego County behavioral health provider directory' })).toHaveAttribute('href', 'https://www.optumsandiego.com/content/SanDiego/sandiego/en/community-resources/providerdirectory1.html')
  expect(countyRequests).toEqual([])
})

test('San Diego city finds its adult clinics but changing county removes them', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'City', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('Escondido')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByRole('heading', { name: /2 adult clinic listings for city Escondido/ })).toBeVisible()
  await page.getByText('Change county').click()
  await page.getByLabel('Choose your county').selectOption('Butte')
  await expect(page.getByRole('heading', { name: /2 adult clinic listings for city Escondido/ })).toHaveCount(0)
  await expect(page.getByText(/Butte County Mental Health Plan/)).toBeVisible()
})

test('county search shows the official mental-health plan access line even without local provider listings', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Colusa')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByText(/Colusa County Mental Health Plan/)).toBeVisible()
  await expect(page.getByText('(888) 793-6580')).toBeVisible()
  await expect(page.getByRole('link', { name: /DHCS county mental health plans/i })).toHaveAttribute('href', 'https://www.dhcs.ca.gov/individuals/county-mental-health-plan-information/')
  await expect(page.getByRole('link', { name: 'Visit Colusa County plan website' })).toHaveCount(0)
})

test('a verified HTTPS county plan landing page is offered without calling it a provider directory', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Butte')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByRole('link', { name: 'Visit Butte County plan website' })).toHaveAttribute('href', 'https://www.buttecounty.net/159/Behavioral-Health')
  await expect(page.getByText('linked by DHCS; not necessarily a provider directory')).toBeVisible()
})

test('a ZIP spanning counties asks the visitor to choose rather than assuming a county or calling LA', async ({ page }) => {
  const requests = []
  page.on('request', (request) => { if (request.url().includes('/api/la-county/locations')) requests.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('90630')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByText(/This ZIP may cross county boundaries/)).toBeVisible()
  await page.getByLabel('Choose your county').selectOption('Orange')
  await expect(page.getByText(/Orange County Mental Health Plan/)).toBeVisible()
  expect(requests).toEqual([])
})

test('ambiguous ZIP can explicitly request the live LA directory after choosing LA', async ({ page }) => {
  const requests = []
  await page.route('**/api/la-county/locations', async (route) => {
    requests.push({ method: route.request().method(), body: route.request().postDataJSON() })
    await route.fulfill({ json: { results: [], hasMore: false } })
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('90630')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await page.getByLabel('Choose your county').selectOption('Los Angeles')
  expect(requests).toEqual([])
  await page.getByRole('button', { name: 'Search live LA County directory' }).click()
  await expect(page.getByText(/0 directory listings for ZIP 90630/)).toBeVisible()
  expect(requests).toHaveLength(1)
  expect(requests[0].method).toBe('POST')
  expect(page.url()).not.toContain('90630')
})

test('visitor can correct a single suggested county without treating its snapshot as comprehensive', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('92708')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByRole('heading', { name: /2 listed provider sites · Fountain Valley/ })).toBeVisible()
  await page.getByText('Change county').click()
  await page.getByLabel('Choose your county').selectOption('Colusa')
  await expect(page.getByText(/Colusa County Mental Health Plan/)).toBeVisible()
  await expect(page.getByRole('heading', { name: /2 listed provider sites · Fountain Valley/ })).toHaveCount(0)
})

test('correcting a city hint removes sites from the previous county', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'City', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('Santa Ana')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByRole('heading', { name: 'Santa Ana', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: /listed provider sites · Orange County/ })).toBeVisible()
  await page.getByText('Change county').click()
  await page.getByLabel('Choose your county').selectOption('Colusa')
  await expect(page.getByRole('heading', { name: /listed provider sites · Orange County/ })).toHaveCount(0)
  await expect(page.getByText(/Colusa County Mental Health Plan/)).toBeVisible()
})

test('footer shows the exact frontend build version after deployment', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('footer')).toContainText(/Version: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}Z · [0-9a-f]{8}/)
})

test('zero state-licensed ZIP matches do not hide separate Orange County sites', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('92708')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByText(/0 statewide licensed-facility listings for zip 92708/)).toHaveCount(0)
  await expect(page.getByText(/No listed facilities in that exact ZIP/)).toHaveCount(0)
  await expect(page.getByRole('heading', { name: /2 listed provider sites · Fountain Valley · Orange County/ })).toBeVisible()
  await expect(page.getByText('CYS Western Youth Services West', { exact: true })).toBeVisible()
  await expect(page.getByText('CYS Western Youth Services West MHSA', { exact: true })).toBeVisible()
  const sourceOrder = await page.locator('section[aria-label="Orange County Behavioral Health Plan sites"]').evaluate((site) => {
    const plan = document.querySelector('section[aria-label="County mental health plan"]')
    return Boolean(plan && site.compareDocumentPosition(plan) & Node.DOCUMENT_POSITION_FOLLOWING)
  })
  expect(sourceOrder).toBe(true)
  await expect(page.getByText(/Orange County access line/)).toBeHidden()
  await page.getByText('County referral · Orange', { exact: true }).click()
  await expect(page.getByText(/Orange County access line/)).toBeVisible()
  await page.locator('section[aria-label="Orange County Behavioral Health Plan sites"]').getByText('Source & details', { exact: true }).click()
  await expect(page.getByRole('link', { name: 'Orange County Behavioral Health Plan provider directory' })).toHaveAttribute('href', 'https://bhpproviderdirectory.ochca.com/')
  await expect(page.getByText(/other licensed facility listings elsewhere in Orange County/)).toBeHidden()
})

test('a ZIP with no exact listings does not present distant county facilities as local results', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('90620')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByText(/No exact ZIP listings were found/)).toBeVisible()
  await expect(page.getByText(/does not mean there is no care nearby/)).toBeVisible()
  const otherCounty = page.getByText(/Other licensed facilities elsewhere in Orange County/)
  await expect(otherCounty).toBeVisible()
  await expect(page.getByText(/ALISO RIDGE BEHAVIORAL HEALTH, LLC/i)).toBeHidden()
  await otherCounty.click()
  await expect(page.getByText(/ALISO RIDGE BEHAVIORAL HEALTH, LLC/i)).toBeVisible()
})

test('unmatched Orange ZIP offers a county-wide provider-site pathway without claiming nearby matches', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('92620')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const elsewhere = page.locator('details[aria-label="Other Orange County provider sites"]')
  await expect(page.getByText(/Orange County Mental Health Plan/)).toBeVisible()
  await expect(page.getByText(/No exact ZIP listings were found/)).toBeVisible()
  await expect(elsewhere).toContainText(/elsewhere in Orange County/)
  await expect(elsewhere.locator('article').first()).toBeHidden()
  await elsewhere.locator(':scope > summary').click()
  await expect(elsewhere.locator('article').first()).toBeVisible()
  await expect(elsewhere).toContainText(/not necessarily near this ZIP/)
  await elsewhere.getByLabel('Show Orange County sites in city').selectOption('Irvine')
  await expect(elsewhere.locator('article')).toHaveCount(1)
  await expect(elsewhere.locator('article').first()).toContainText('Irvine')
  await expect(elsewhere.getByText('Woodland Hills')).toHaveCount(0)
})

test('unmatched San Diego ZIP offers adult clinics elsewhere in county without implying ZIP proximity', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('92037')
  await page.getByRole('button', { name: 'Find support options' }).click()
  const elsewhere = page.locator('details[aria-label="Other San Diego County adult clinics"]')
  await expect(page.getByText(/San Diego County Mental Health Plan/)).toBeVisible()
  await expect(elsewhere).toContainText(/elsewhere in San Diego County/)
  await expect(elsewhere.locator('article').first()).toBeHidden()
  await elsewhere.locator(':scope > summary').click()
  await expect(elsewhere.locator('article').first()).toBeVisible()
  await elsewhere.getByLabel('Show San Diego adult clinics in city').selectOption('Escondido')
  await expect(elsewhere.locator('article')).toHaveCount(2)
})

test('ambiguous ZIP does not select a county-wide site list until visitor chooses county', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('90630')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.locator('details[aria-label="Other Orange County provider sites"]')).toHaveCount(0)
  await page.getByLabel('Choose your county').selectOption('Orange')
  await expect(page.locator('details[aria-label="Other Orange County provider sites"]')).toBeVisible()
})

test('unmapped ZIP does not fabricate a California county and still offers a manual contact pathway', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'ZIP code', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('99999')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByText(/cannot confirm this ZIP belongs to California/)).toBeVisible()
  await expect(page.locator('section[aria-label="County mental health plan"]')).toHaveCount(0)
  await page.getByLabel('Choose your county').selectOption('Butte')
  await expect(page.locator('section[aria-label="County mental health plan"]')).toContainText('(800) 334-6622')
})

test('Orange network site physically outside Orange does not create a false Orange city hint', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'City', exact: true }).click()
  await page.getByRole('textbox', { name: /^California (city|ZIP code)$/ }).fill('Woodland Hills')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.locator('section[aria-label="Orange County Behavioral Health Plan sites"]')).toHaveCount(0)
  await expect(page.getByText(/Suggested county: Orange/)).toHaveCount(0)
})
