import { test, expect } from '@playwright/test'

for (const width of [320, 390, 1440]) {
  test(`gentle sprout stays decorative and preserves crisis access at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/')
    await expect(page.getByText('Take your time. One small step is enough to begin.')).toBeVisible()
    const sprout = page.locator('main section').first().locator('svg')
    await expect(sprout).toHaveAttribute('data-sprout', 'wave')
    await expect(page.locator('[data-sprout-speech]')).toHaveCount(3)
    await expect(page.locator('[data-sprout="hug"]')).toHaveCount(1)
    await expect(page.locator('[data-sprout="read"]')).toHaveCount(1)
    await expect(page.locator('footer [data-sprout="bloom"]')).toHaveCount(1)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByRole('heading', {name:'You are not alone.',level:1})).toBeVisible()
    const hero = page.locator('main section').first()
    const bubble = hero.locator('[data-speech-bubble]')
    await expect(bubble.getByRole('heading', {name:'You are not alone.',level:1})).toBeVisible()
    await expect(bubble.getByText('Find free crisis and support resources, or explore in-person options whose cost and eligibility you must confirm.', {exact:true})).toBeVisible()
    const speech = await hero.locator('[data-sprout-speech]').boundingBox()
    expect(Math.abs(speech.x + speech.width / 2 - width / 2)).toBeLessThan(2)
    expect(await hero.locator('[data-sprout-speech]').evaluate(e=>getComputedStyle(e).flexDirection)).toBe('row')
    const mascot = await sprout.boundingBox()
    const bubbleBox = await bubble.boundingBox()
    expect(mascot.x + mascot.width).toBeLessThan(bubbleBox.x)
    await expect(page.getByText(/Optional · asks permission first/)).toHaveCount(0)
    await expect(page.getByText(/Choose a county for its Medi-Cal mental-health contact and available listings/)).toHaveCount(0)
    await expect(sprout).toHaveAttribute('aria-hidden', 'true')
    await expect(sprout).toHaveAttribute('focusable', 'false')
    expect(await sprout.evaluate(el => getComputedStyle(el).animationName)).toBe('none')
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
    const crisis = page.getByRole('link', { name: 'Call 988 now' })
    await expect(crisis).toHaveAttribute('href', 'tel:988')
    expect(await crisis.evaluate(el => el.getBoundingClientRect().bottom < innerHeight)).toBe(true)
    await page.getByRole('searchbox', { name: 'Search' }).fill('no matching resource')
    await expect(page.getByText('No matches this time. Try fewer filters, or browse all resources.')).toBeVisible()
    await page.getByRole('button', { name: 'Clear filters' }).last().click()
    await expect(page.getByText('Showing 20 of 23 resources')).toBeVisible()
  })
}

test('sparse county offers a gentle but accurate next step', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('California county').selectOption('Colusa')
  await page.getByRole('button', { name: 'Find support options' }).click()
  await expect(page.getByRole('status')).toContainText('That does not mean no care is available')
  await expect(page.getByRole('link', { name: 'Call county plan' })).toBeVisible()
  await expect(page.locator('section[aria-labelledby="local-support-heading"]').getByRole('link', { name: 'Call 211', exact: true })).toBeVisible()
})
